# import pandas library

In [39]:
import pandas as pd

# read data from files

In [40]:
df = pd.read_csv(r"C:\Users\dellp\Downloads\data.csv")
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

# create series and dataframe

In [41]:
# from list
pd.Series([6,1,"8",1,1.2],index = [1,2,3,4,5])

1      6
2      1
3      8
4      1
5    1.2
dtype: object

In [42]:
#from dictionary
pd.Series({1:23,
          2:45,
          3:21})

1    23
2    45
3    21
dtype: int64

In [43]:
# create dataframe
data = {"name":["x","y","z"],
       "age":[19,15,20],
       "gender":["m","f","m"]}
d = pd.DataFrame(data)

In [44]:
d

  name  age gender
0    x   19      m
1    y   15      f
2    z   20      m

# Save output

In [45]:
d.to_csv("df.csv")

# head, tail, info, describe, shape, columns

In [46]:
df.head() # top 5 rows

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [47]:
df.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [48]:
#if want to change data type of any column

In [49]:
df.tail() # bottom 5 rows

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [50]:
df.shape # shape of dataframe

(32, 5)

In [51]:
df.columns # list of columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [52]:
df.info() # info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [53]:
df.describe() # stats of numeric values only

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

# read function take first row of data as an header and if data has no columns name in this case no need of header

In [54]:
df = pd.read_csv(r"C:\Users\dellp\Downloads\titanic.csv",header = None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## if want to give column name

In [55]:
df = pd.read_csv(r"C:\Users\dellp\Downloads\titanic.csv",names =["a","b","c","place","d","e","f","g","h","i","j","k"])
df.head()

,a,b,c,place,d,e,f,g,h,i,j,k
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [56]:
# if given name is less than no. of column then the first remaining columns consider as row index

In [57]:
# if given name is more than no. of column then create a columns with all row value as nan

# csv seperatar

In [58]:
# if have csv file where is data is not seperated by comman and sep by @

In [59]:
# pd.read_csv("text.csx",sep = "@")

In [60]:
df = pd.read_csv(r"C:\Users\dellp\Downloads\titanic.csv",header = None , skiprows = [1,3])

In [61]:
df

,0,1,2,3,4,5,6,7,8,9,10,11
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
2,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
6,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
7,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
8,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
9,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

# view

In [62]:
df = pd.read_csv(r"C:\Users\dellp\Downloads\data.csv")

In [63]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [64]:
df[["Date","Maxpulse"]].head()

           Date  Maxpulse
0  '2020/12/01'       130
1  '2020/12/02'       145
2  '2020/12/03'       135
3  '2020/12/04'       175
4  '2020/12/05'       148

In [65]:
a = df[["Date","Maxpulse"]].head()
type(a)

pandas.core.frame.DataFrame

# if excel file have multiple sheet how we access

In [69]:
df = pd.read_excel(r"C:\Users\dellp\Downloads\data1.xlsx",sheet_name = "data1")

In [70]:
df

   sdss    dssd      dds
0     1   dhdds   sjfdfh
1     5  ddsnnh      fdn
2     2  dshbnd     dmfm
3     3    dbsn  fgd ffg
4     2   fs fn      gdk

# if want to access all sheet and read data

In [82]:
df = pd.ExcelFile(r"C:\Users\dellp\Downloads\data1.xlsx")

In [83]:
df.sheet_names

['data1']

In [85]:
for i in df.sheet_names:
    print(pd.read_excel(r"C:\Users\dellp\Downloads\data1.xlsx", sheet_name = i))

   sdss    dssd      dds
0     1   dhdds   sjfdfh
1     5  ddsnnh      fdn
2     2  dshbnd     dmfm
3     3    dbsn  fgd ffg
4     2   fs fn      gdk

In [86]:
# direct load data from github 
# pd.read_csv("address")