In [1]:
import pandas as pd

In [100]:
df = pd.read_csv("addresses.csv")

In [101]:
df

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [102]:
data = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")

In [103]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [104]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [105]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [106]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [107]:
data[["Name","Sex","Ticket"]].describe()

                           Name   Sex  Ticket
count                       891   891     891
unique                      891     2     681
top     Braund, Mr. Owen Harris  male  347082
freq                          1   577       7

In [108]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

# filter that columns which datatype is object

In [109]:
type(data.dtypes)

pandas.core.series.Series

In [110]:
data["Fare"]

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [111]:
type(data["Fare"])

pandas.core.series.Series

In [112]:
data.dtypes == "object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [113]:
data.dtypes[data.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [114]:
data[data.dtypes[data.dtypes == "object"].index]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [115]:
data[data.dtypes[data.dtypes == "object"].index].describe()

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

# data where survive is 0

In [116]:
data[data["Survived"]==0]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [117]:
# people survived and its male
data[(data["Survived"]==0) & (data["Sex"]=="male")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [118]:
len(data[(data["Survived"]==0) & (data["Sex"]=="male")])

468

In [119]:
len(data[(data["Survived"]==0) & (data["Sex"]=="female")])

81

In [120]:
# no of male on ship 
len(data[data["Sex"]=="male"])

577

In [121]:
# no of female on ship 
len(data[data["Sex"]=="female"])

314

In [122]:
data["Sex"].value_counts() # groupby count is here

Sex
male      577
female    314
Name: count, dtype: int64

In [123]:
#max fare person paid
data[data["Fare"]== max(data["Fare"])]["Name"]

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [124]:
data[["Sex","Survived"]].value_counts()

Sex     Survived
male    0           468
female  1           233
male    1           109
female  0            81
Name: count, dtype: int64

In [125]:
data[data["Fare"]== 0] # minimum paid

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0,NaN,S
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0,NaN,S
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0,NaN,S
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0,NaN,S
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0,NaN,S
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0,NaN,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0,NaN,S
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0,NaN,S
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0,NaN,S
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0,NaN,S
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0,A36,S
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0,NaN,S

In [126]:
len(data[data["Cabin"] != None]) # no.of people have not cabin

891

In [127]:
 len(data[data["Cabin"].isnull() == True])# no.of people have not cabin

687

# create new column

In [128]:
data["ship name"] = "titanic"

In [129]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ship name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,titanic
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,titanic
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,titanic
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,titanic
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,titanic

# delete column

In [130]:
data = data.drop("ship name", axis = 1) # for save after drop 2 option    store in same variable or inpplace = True

In [131]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# delete row

In [132]:
data = data.drop(0) # 0 is index

# row vise access data

In [133]:
data.iloc[0]  # iloc takes default indexes

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object

In [134]:
data.loc[2] # loc takes the named indexes

PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                              26.0
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object

In [135]:
data.loc[1:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [136]:
data.loc[101:106,['Survived',"Age"]]

     Survived   Age
101         0   NaN
102         0  21.0
103         0  33.0
104         0  37.0
105         0  28.0
106         1  21.0

In [137]:
data.loc[3:4,["Fare","Cabin","Embarked"]]

    Fare Cabin Embarked
3  53.10  C123        S
4   8.05   NaN        S

In [138]:
data.iloc[3:4,["Fare","Cabin","Embarked"]] # because iloc takes default indexs even in case of column (means numeric)

IndexError: .iloc requires numeric indexers, got ['Fare' 'Cabin' 'Embarked']

In [139]:
data.iloc[3:5,[9,10,11]]

     Fare Cabin Embarked
4  8.0500   NaN        S
5  8.4583   NaN        Q

In [140]:
data.loc[:,["PassengerId","Pclass"]]

     PassengerId  Pclass
1              2       1
2              3       3
3              4       1
4              5       3
5              6       3
..           ...     ...
886          887       2
887          888       1
888          889       3
889          890       1
890          891       3

[890 rows x 2 columns]

In [141]:
data.iloc[:,[0,2]]

     PassengerId  Pclass
1              2       1
2              3       3
3              4       1
4              5       3
5              6       3
..           ...     ...
886          887       2
887          888       1
888          889       3
889          890       1
890          891       3

[890 rows x 2 columns]

In [142]:
# all record where age > 35
data[data["Age"]>35]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q

In [143]:
data1  = data.iloc[1:10,[0,2,10]]

In [144]:
data1

    PassengerId  Pclass Cabin
2             3       3   NaN
3             4       1  C123
4             5       3   NaN
5             6       3   NaN
6             7       1   E46
7             8       3   NaN
8             9       3   NaN
9            10       2   NaN
10           11       3    G6

In [145]:
# change index name 
data1.set_index("PassengerId",inplace=True)  # if we want to set passengerid column as index

In [146]:
# drop all record where is nan
data1.dropna()

             Pclass Cabin
PassengerId
4                 1  C123
7                 1   E46
11                3    G6

In [147]:
# drop column where nan is available
data1.dropna(axis=1)

             Pclass
PassengerId
3                 3
4                 1
5                 3
6                 3
7                 1
8                 3
9                 3
10                2
11                3

In [148]:
data1

             Pclass Cabin
PassengerId
3                 3   NaN
4                 1  C123
5                 3   NaN
6                 3   NaN
7                 1   E46
8                 3   NaN
9                 3   NaN
10                2   NaN
11                3    G6

In [149]:
data1.dropna(axis = 1 ,thresh = 2) # atleast 2 non na value required to keep it

             Pclass Cabin
PassengerId
3                 3   NaN
4                 1  C123
5                 3   NaN
6                 3   NaN
7                 1   E46
8                 3   NaN
9                 3   NaN
10                2   NaN
11                3    G6

In [150]:
data1.dropna(axis = 1 ,thresh = 7) # atleast 2 non na value required to keep it

             Pclass
PassengerId
3                 3
4                 1
5                 3
6                 3
7                 1
8                 3
9                 3
10                2
11                3

In [151]:
# fill Nan Value
data1["Cabin"].fillna(data1["Pclass"].mean())

PassengerId
3     2.444444
4         C123
5     2.444444
6     2.444444
7          E46
8     2.444444
9     2.444444
10    2.444444
11          G6
Name: Cabin, dtype: object

In [152]:
data1

             Pclass Cabin
PassengerId
3                 3   NaN
4                 1  C123
5                 3   NaN
6                 3   NaN
7                 1   E46
8                 3   NaN
9                 3   NaN
10                2   NaN
11                3    G6

In [153]:
data2 =  data.loc[0:10,["Age","Sex","Fare"]]

In [154]:
data2

     Age     Sex     Fare
1   38.0  female  71.2833
2   26.0  female   7.9250
3   35.0  female  53.1000
4   35.0    male   8.0500
5    NaN    male   8.4583
6   54.0    male  51.8625
7    2.0    male  21.0750
8   27.0  female  11.1333
9   14.0  female  30.0708
10   4.0  female  16.7000

In [155]:
data2.groupby("Sex").mean()

              Age       Fare
Sex
female  24.000000  31.702067
male    30.333333  22.361450

In [156]:
# total revenue from male or female
data2.groupby("Sex").sum()["Fare"]

Sex
female    190.2124
male       89.4458
Name: Fare, dtype: float64

In [157]:
data1

             Pclass Cabin
PassengerId
3                 3   NaN
4                 1  C123
5                 3   NaN
6                 3   NaN
7                 1   E46
8                 3   NaN
9                 3   NaN
10                2   NaN
11                3    G6

In [158]:
data1["new"]= data1["Pclass"]/3

In [159]:
data1

             Pclass Cabin       new
PassengerId
3                 3   NaN  1.000000
4                 1  C123  0.333333
5                 3   NaN  1.000000
6                 3   NaN  1.000000
7                 1   E46  0.333333
8                 3   NaN  1.000000
9                 3   NaN  1.000000
10                2   NaN  0.666667
11                3    G6  1.000000

# how to apply function on dataframe

In [160]:
data1["new"]= data1["Pclass"].apply(lambda x : x/2)

In [161]:
data1

             Pclass Cabin  new
PassengerId
3                 3   NaN  1.5
4                 1  C123  0.5
5                 3   NaN  1.5
6                 3   NaN  1.5
7                 1   E46  0.5
8                 3   NaN  1.5
9                 3   NaN  1.5
10                2   NaN  1.0
11                3    G6  1.5

In [162]:
def function(x):
    return x/5

In [163]:
data1["new"] = data1["new"].apply(function)

In [164]:
data1

             Pclass Cabin  new
PassengerId
3                 3   NaN  0.3
4                 1  C123  0.1
5                 3   NaN  0.3
6                 3   NaN  0.3
7                 1   E46  0.1
8                 3   NaN  0.3
9                 3   NaN  0.3
10                2   NaN  0.2
11                3    G6  0.3

In [165]:
data3 = data.loc[0:5,["PassengerId","Name","Sex","Age"]]

In [166]:
data3

,PassengerId,Name,Sex,Age
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
2,3,"Heikkinen, Miss. Laina",female,26.0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,5,"Allen, Mr. William Henry",male,35.0
5,6,"Moran, Mr. James",male,NaN

In [167]:
# add column contain len of name
data3["len"] = data3["Name"].apply(len)

In [168]:
data3

,PassengerId,Name,Sex,Age,len
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,51
2,3,"Heikkinen, Miss. Laina",female,26.0,22
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,44
4,5,"Allen, Mr. William Henry",male,35.0,24
5,6,"Moran, Mr. James",male,NaN,16

In [169]:
import math
def log(x):
    if x<=3:
        return x
    else:
        return math.log10(x)

In [170]:
data3["PassengerId_filter"]=data3["PassengerId"].apply(log)

In [171]:
data3

,PassengerId,Name,Sex,Age,len,PassengerId_filter
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,51,2.000000
2,3,"Heikkinen, Miss. Laina",female,26.0,22,3.000000
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,44,0.602060
4,5,"Allen, Mr. William Henry",male,35.0,24,0.698970
5,6,"Moran, Mr. James",male,NaN,16,0.778151

In [172]:
data1

             Pclass Cabin  new
PassengerId
3                 3   NaN  0.3
4                 1  C123  0.1
5                 3   NaN  0.3
6                 3   NaN  0.3
7                 1   E46  0.1
8                 3   NaN  0.3
9                 3   NaN  0.3
10                2   NaN  0.2
11                3    G6  0.3

In [173]:
data3

,PassengerId,Name,Sex,Age,len,PassengerId_filter
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,51,2.000000
2,3,"Heikkinen, Miss. Laina",female,26.0,22,3.000000
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,44,0.602060
4,5,"Allen, Mr. William Henry",male,35.0,24,0.698970
5,6,"Moran, Mr. James",male,NaN,16,0.778151

# concatenate

In [175]:
pd.concat([data1,data3]) # horizontal concat

,Pclass,Cabin,new,PassengerId,Name,Sex,Age,len,PassengerId_filter
3,3.0,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,C123,0.1,NaN,NaN,NaN,NaN,NaN,NaN
5,3.0,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN
6,3.0,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN
7,1.0,E46,0.1,NaN,NaN,NaN,NaN,NaN,NaN
8,3.0,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN
9,3.0,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN
10,2.0,NaN,0.2,NaN,NaN,NaN,NaN,NaN,NaN
11,3.0,G6,0.3,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,2.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,51.0,2.000000
2,NaN,NaN,NaN,3.0,"Heikkinen, Miss. Laina",female,26.0,22.0,3.000000
3,NaN,NaN,NaN,4.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,44.0,0.602060
4,NaN,NaN,NaN,5.0,"Allen, Mr. William Henry",male,35.0,24.0,0.698970
5,NaN,NaN,NaN,6.0,"Moran, Mr. James",male,NaN,16.0,0.778151

In [176]:
pd.concat([data1,data3],axis = 1) # vertical concat

,Pclass,Cabin,new,PassengerId,Name,Sex,Age,len,PassengerId_filter
3,3.0,NaN,0.3,4.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,44.0,0.602060
4,1.0,C123,0.1,5.0,"Allen, Mr. William Henry",male,35.0,24.0,0.698970
5,3.0,NaN,0.3,6.0,"Moran, Mr. James",male,NaN,16.0,0.778151
6,3.0,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN
7,1.0,E46,0.1,NaN,NaN,NaN,NaN,NaN,NaN
8,3.0,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN
9,3.0,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN
10,2.0,NaN,0.2,NaN,NaN,NaN,NaN,NaN,NaN
11,3.0,G6,0.3,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,2.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,51.0,2.000000
2,NaN,NaN,NaN,3.0,"Heikkinen, Miss. Laina",female,26.0,22.0,3.000000

In [177]:
def category(x):
    if x<100:
        return "A"
    elif x<200:
        return "B"
    else:
        return "C"

In [178]:
data["category_by_fare"]= data["Fare"].apply(category)

In [179]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,category_by_fare
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,A
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,A
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,A
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,A
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,A
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,A
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,A
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,A
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,A