In [1]:
import pandas as pd

In [2]:
d1  = {'key1' : [1,2,3,4,5],
      "key2" : [6,7,8,9,10],
      "key3" : [11,12,13,"ash",15]}

In [3]:
data1 = pd.DataFrame(d1)

In [9]:
d2  = {'key1' : [1,2,"ap",4,5],
      "key2" : [6,7,"sd",9,10],
      "key3" : [11,"as",13,"ash",15]}

In [10]:
data2 = pd.DataFrame(d2)

In [11]:
print(data1)
print(data2)

   key1  key2 key3
0     1     6   11
1     2     7   12
2     3     8   13
3     4     9  ash
4     5    10   15
  key1 key2 key3
0    1    6   11
1    2    7   as
2   ap   sd   13
3    4    9  ash
4    5   10   15

In [14]:
pd.merge(data1,data2)  # by default how = inner     inner like intersection in set       data1 consider as left and other right

  key1 key2 key3
0    1    6   11
1    4    9  ash
2    5   10   15

In [15]:
pd.merge(data1,data2,how = "inner",on = "key1")

  key1  key2_x key3_x key2_y key3_y
0    1       6     11      6     11
1    2       7     12      7     as
2    4       9    ash      9    ash
3    5      10     15     10     15

In [16]:
pd.merge(data1,data2,how = "left",on = "key1")

  key1  key2_x key3_x key2_y key3_y
0    1       6     11      6     11
1    2       7     12      7     as
2    3       8     13    NaN    NaN
3    4       9    ash      9    ash
4    5      10     15     10     15

In [17]:
pd.merge(data1,data2,how = "right",on = "key1")

  key1  key2_x key3_x key2_y key3_y
0    1     6.0     11      6     11
1    2     7.0     12      7     as
2   ap     NaN    NaN     sd     13
3    4     9.0    ash      9    ash
4    5    10.0     15     10     15

In [18]:
pd.merge(data1,data2,how = "outer",on = "key1")

  key1  key2_x key3_x key2_y key3_y
0    1     6.0     11      6     11
1    2     7.0     12      7     as
2    3     8.0     13    NaN    NaN
3    4     9.0    ash      9    ash
4    5    10.0     15     10     15
5   ap     NaN    NaN     sd     13

In [20]:
d1  = {'a' : [1,2,3,4,5],
      "b" : [6,7,8,9,10],
      "c" : [11,12,13,"ash",15]}

d2  = {'key1' : [1,2,"ap",4,5],
      "key2" : [6,7,"sd",9,10],
      "key3" : [11,"as",13,"ash",15]}

df11 = pd.DataFrame(d1)
df12 = pd.DataFrame(d2)

# how to join when not any column name is common in both dataframe

In [22]:
pd.merge(df11,df12,how="inner",on= "key1")

KeyError: 'key1'

In [23]:
pd.merge(df11,df12,how="inner",left_on= "a", right_on = "key1")

   a   b    c key1 key2 key3
0  1   6   11    1    6   11
1  2   7   12    2    7   as
2  4   9  ash    4    9  ash
3  5  10   15    5   10   15

In [24]:
df11

   a   b    c
0  1   6   11
1  2   7   12
2  3   8   13
3  4   9  ash
4  5  10   15

In [25]:
df12

  key1 key2 key3
0    1    6   11
1    2    7   as
2   ap   sd   13
3    4    9  ash
4    5   10   15

# join always try to focus on index and merge focus on column name

In [29]:
# join work when col name of each df is different but in merge not get problem

In [28]:
df11.join(df12)

   a   b    c key1 key2 key3
0  1   6   11    1    6   11
1  2   7   12    2    7   as
2  3   8   13   ap   sd   13
3  4   9  ash    4    9  ash
4  5  10   15    5   10   15

# insert column

In [30]:
df11

   a   b    c
0  1   6   11
1  2   7   12
2  3   8   13
3  4   9  ash
4  5  10   15

In [31]:
df11.insert(1,"abc",df11["a"]*2)

In [32]:
df11

   a  abc   b    c
0  1    2   6   11
1  2    4   7   12
2  3    6   8   13
3  4    8   9  ash
4  5   10  10   15

# update value in dataframe

In [33]:
df11.loc[2,"b"]= 1000

In [34]:
df11

   a  abc     b    c
0  1    2     6   11
1  2    4     7   12
2  3    6  1000   13
3  4    8     9  ash
4  5   10    10   15