In [1]:
import pandas as pd

In [2]:
d1  = {'key1' : [1,2,3,4,5],
      "key2" : [6,7,8,9,10],
      "key3" : [11,12,13,"ash",15]}

In [3]:
data1 = pd.DataFrame(d1)

In [9]:
d2  = {'key1' : [1,2,"ap",4,5],
      "key2" : [6,7,"sd",9,10],
      "key3" : [11,"as",13,"ash",15]}

In [10]:
data2 = pd.DataFrame(d2)

In [11]:
print(data1)
print(data2)

   key1  key2 key3
0     1     6   11
1     2     7   12
2     3     8   13
3     4     9  ash
4     5    10   15
  key1 key2 key3
0    1    6   11
1    2    7   as
2   ap   sd   13
3    4    9  ash
4    5   10   15

In [14]:
pd.merge(data1,data2)  # by default how = inner     inner like intersection in set       data1 consider as left and other right

  key1 key2 key3
0    1    6   11
1    4    9  ash
2    5   10   15

In [15]:
pd.merge(data1,data2,how = "inner",on = "key1")

  key1  key2_x key3_x key2_y key3_y
0    1       6     11      6     11
1    2       7     12      7     as
2    4       9    ash      9    ash
3    5      10     15     10     15

In [16]:
pd.merge(data1,data2,how = "left",on = "key1")

  key1  key2_x key3_x key2_y key3_y
0    1       6     11      6     11
1    2       7     12      7     as
2    3       8     13    NaN    NaN
3    4       9    ash      9    ash
4    5      10     15     10     15

In [17]:
pd.merge(data1,data2,how = "right",on = "key1")

  key1  key2_x key3_x key2_y key3_y
0    1     6.0     11      6     11
1    2     7.0     12      7     as
2   ap     NaN    NaN     sd     13
3    4     9.0    ash      9    ash
4    5    10.0     15     10     15

In [18]:
pd.merge(data1,data2,how = "outer",on = "key1")

  key1  key2_x key3_x key2_y key3_y
0    1     6.0     11      6     11
1    2     7.0     12      7     as
2    3     8.0     13    NaN    NaN
3    4     9.0    ash      9    ash
4    5    10.0     15     10     15
5   ap     NaN    NaN     sd     13

In [20]:
d1  = {'a' : [1,2,3,4,5],
      "b" : [6,7,8,9,10],
      "c" : [11,12,13,"ash",15]}

d2  = {'key1' : [1,2,"ap",4,5],
      "key2" : [6,7,"sd",9,10],
      "key3" : [11,"as",13,"ash",15]}

df11 = pd.DataFrame(d1)
df12 = pd.DataFrame(d2)

# how to join when not any column name is common in both dataframe

In [22]:
pd.merge(df11,df12,how="inner",on= "key1")

KeyError: 'key1'

In [23]:
pd.merge(df11,df12,how="inner",left_on= "a", right_on = "key1")

   a   b    c key1 key2 key3
0  1   6   11    1    6   11
1  2   7   12    2    7   as
2  4   9  ash    4    9  ash
3  5  10   15    5   10   15

In [24]:
df11

   a   b    c
0  1   6   11
1  2   7   12
2  3   8   13
3  4   9  ash
4  5  10   15

In [25]:
df12

  key1 key2 key3
0    1    6   11
1    2    7   as
2   ap   sd   13
3    4    9  ash
4    5   10   15

# join always try to focus on index and merge focus on column name

In [29]:
# join work when col name of each df is different but in merge not get problem

In [28]:
df11.join(df12)

   a   b    c key1 key2 key3
0  1   6   11    1    6   11
1  2   7   12    2    7   as
2  3   8   13   ap   sd   13
3  4   9  ash    4    9  ash
4  5  10   15    5   10   15

# insert column

In [30]:
df11

   a   b    c
0  1   6   11
1  2   7   12
2  3   8   13
3  4   9  ash
4  5  10   15

In [31]:
df11.insert(1,"abc",df11["a"]*2)

In [32]:
df11

   a  abc   b    c
0  1    2   6   11
1  2    4   7   12
2  3    6   8   13
3  4    8   9  ash
4  5   10  10   15

# update value in dataframe

In [33]:
df11.loc[2,"b"]= 1000

In [34]:
df11

   a  abc     b    c
0  1    2     6   11
1  2    4     7   12
2  3    6  1000   13
3  4    8     9  ash
4  5   10    10   15

In [1]:
import numpy as np
import pandas as pd

In [2]:
l = [1,2,2,4,5,2]

In [3]:
type(l)

list

In [4]:
a = np.array(l)

In [5]:
type(a)

numpy.ndarray

In [6]:
a1 =np.array([[1,2,3],[4,5,6]])

In [7]:
a2  =np.array([[[1,2,3],[7,8,9]],[[4,5,6],[1,5,9]]])

# check dim of array

In [8]:
a.ndim

1

In [9]:
a1.ndim

2

In [10]:
a2.ndim

3

In [11]:
a2

array([[[1, 2, 3],
        [7, 8, 9]],

       [[4, 5, 6],
        [1, 5, 9]]])

In [12]:
# asarray, asmatrix

In [13]:
l  = [1,2,3,3]

In [14]:
np.asarray(l) # only one d

array([1, 2, 3, 3])

In [15]:
np.asmatrix(l) # atleast 2d

matrix([[1, 2, 3, 3]])

# deep copy and shallow copy

In [16]:
a

array([1, 2, 2, 4, 5, 2])

In [17]:
a1 =a # shallow copy if make change in any of them make changes in both

In [18]:
a1

array([1, 2, 2, 4, 5, 2])

In [19]:
a[0]

np.int64(1)

In [20]:
a[0]=10

In [21]:
a

array([10,  2,  2,  4,  5,  2])

In [22]:
a1

array([10,  2,  2,  4,  5,  2])

In [23]:
a[1]=50

In [24]:
a

array([10, 50,  2,  4,  5,  2])

In [25]:
a1

array([10, 50,  2,  4,  5,  2])

In [26]:
a2  =np.copy(a) # deep copy

In [27]:
a2

array([10, 50,  2,  4,  5,  2])

In [28]:
a2[1]= 100

In [29]:
a2

array([ 10, 100,   2,   4,   5,   2])

In [30]:
a

array([10, 50,  2,  4,  5,  2])

# from function

In [31]:
np.fromfunction(lambda i,j : i==j,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [32]:
np.random.rand(3,2)

array([[0.49392887, 0.53376592],
       [0.233076  , 0.03019734],
       [0.8919386 , 0.56284901]])

In [33]:
np.random.rand(4,3,2) #(z,x,y)

array([[[0.15905582, 0.4883729 ],
        [0.46547498, 0.6079181 ],
        [0.08089889, 0.34227803]],

       [[0.82848997, 0.74934567],
        [0.44068125, 0.93898905],
        [0.38450578, 0.87971239]],

       [[0.096722  , 0.28089066],
        [0.34936855, 0.25489163],
        [0.66685293, 0.02033032]],

       [[0.7289346 , 0.07393875],
        [0.3072951 , 0.95948871],
        [0.86049548, 0.03633196]]])

In [34]:
np.random.randn(4,3,2)# randn generate with mean  = 0  , std = 1

array([[[ 0.49728997,  0.01534496],
        [ 1.44584615,  0.33532253],
        [ 0.32308684,  1.7919504 ]],

       [[-0.57232454,  1.97640519],
        [-1.424585  ,  0.54056946],
        [-0.09549453,  0.60300256]],

       [[-1.93682526, -1.50954077],
        [-0.28565928,  0.27538914],
        [ 1.01590016,  0.38326838]],

       [[ 1.57391336,  1.17528636],
        [-0.08071137,  0.01041141],
        [-0.04506329, -0.15369761]]])

In [35]:
np.random.randint(0,10,(4,2,5)) # between 0 and 10 matrix z,x,y

array([[[7, 4, 5, 7, 2],
        [8, 6, 4, 5, 2]],

       [[6, 8, 4, 4, 0],
        [0, 9, 6, 8, 9]],

       [[4, 9, 2, 2, 3],
        [4, 0, 4, 0, 1]],

       [[2, 1, 7, 1, 8],
        [2, 1, 0, 3, 3]]], dtype=int32)

# nd convert to 2d array

In [36]:
d =np.random.randint(0,10,(4,2,5))

In [37]:
d

array([[[5, 3, 2, 7, 7],
        [7, 0, 3, 8, 2]],

       [[4, 0, 3, 3, 6],
        [4, 4, 1, 4, 1]],

       [[0, 0, 8, 7, 1],
        [6, 5, 2, 5, 5]],

       [[1, 0, 3, 1, 8],
        [1, 7, 2, 4, 2]]], dtype=int32)

In [38]:
pd.DataFrame(d)

ValueError: Must pass 2-d input. shape=(4, 2, 5)

In [42]:
np.reshape(d,(8,5))

array([[5, 3, 2, 7, 7],
       [7, 0, 3, 8, 2],
       [4, 0, 3, 3, 6],
       [4, 4, 1, 4, 1],
       [0, 0, 8, 7, 1],
       [6, 5, 2, 5, 5],
       [1, 0, 3, 1, 8],
       [1, 7, 2, 4, 2]], dtype=int32)

In [43]:
d.reshape(8,-2)

array([[5, 3, 2, 7, 7],
       [7, 0, 3, 8, 2],
       [4, 0, 3, 3, 6],
       [4, 4, 1, 4, 1],
       [0, 0, 8, 7, 1],
       [6, 5, 2, 5, 5],
       [1, 0, 3, 1, 8],
       [1, 7, 2, 4, 2]], dtype=int32)